wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss_step
      5: 1
      6:
      - 1
    - 1: train/acc_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/acc
      5: 1
      6:
      - 1
    - 1: train/loss_epoch
      5: 1
      6:
      - 1
    - 1: train/acc_epoch
      5: 1
      6:
      - 1
    python_version: 3.8.10
    start_time: 1664465475.936464
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.13.3
      8:
      - 5
      - 9
